# Generated by Django 4.0.3 on 2022-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('color', models.CharField(max_length=30)),
                ('stared', models.BooleanField(default=False)),
            ],
        ),
    ]
