# Generated by Django 4.0.3 on 2022-05-21 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='stared',
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#11998e, #38ef7d', 'GREEN'), ('#4e54c8, #8f94fb', 'BLUE'), ('#ed213a, #93291e', 'RED'), ('#fdc830, #f37335', 'ORANGE'), ('#000000, #434343', 'BLACK'), ('#2193b0, #6dd5ed', 'SKY BLUE'), ('#bc4e9c, #f80759', 'PINK')], max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 21)),
        ),
    ]
